apiVersion: apps/v1
kind: Deployment
metadata:
    name: mople-dev
    labels:
        app: mople-dev
    namespace: mople
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mople-dev
    template:
        metadata:
            labels:
                app: mople-dev
        spec:
            affinity:
                podAntiAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                        - podAffinityTerm:
                              labelSelector:
                                  matchExpressions:
                                      - key: key
                                        operator: In
                                        values:
                                            - worker1
                              topologyKey: kubernetes.io/hostname
                          weight: 100
            containers:
                - name: mople-dev
                  image: kmdy7991/groupmeet:2.7
                  env:
                      - name: JAVA_TOOL_OPTIONS
                        value: '-Duser.timezone=Asia/Seoul'
                      - name: PROFILE
                        value: 'dev'
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8284
                  resources:
                      requests:
                          memory: 256Mi
                      limits:
                          memory: 512Mi